'use client';

import './globals.css';
import type { Metadata } from 'next';
import CustomProvider from '@/components/redux/CustomProvider';
import Layout from '@/styles/styledComponents/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PureFunctionProp) {
  return (
    <html lang="en">
      <body>
        <CustomProvider>
          <Layout>{children}</Layout>
        </CustomProvider>
      </body>
    </html>
  );
}
