'use client';

import './globals.css';
import type { Metadata } from 'next';
import CustomProvider from '@/components/redux/CustomProvider';
import LayoutContainer from '@/styles/styledComponents/layout';
import NavBar from '@/components/shared/navBar/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PureFunctionProp) {
  return (
    <html lang="en">
      <body>
        <CustomProvider>
          <LayoutContainer>
            <NavBar />
            {children}
          </LayoutContainer>
        </CustomProvider>
      </body>
    </html>
  );
}
